### ISSUE TITLE
[HOW TO JOIN]: Question about this

### ISSUE THREAD

**Issue by rafiddewan** [ScottKwang/CodeWithFriends-Spring2020#2]
[How to Join](https://github.com/rafiddewan/CodeWithFriends-Spring2020/blob/master/how_to_join.md)

Hi Mayuko and Scott,

It says: Add a directory under the projects/ directory named after your git user.
Where can we find the projects/ directory?

**Comment by rafiddewan** [comment]
Do we create the projects/ directory ourselves?

**Comment by ScottBrenner** [comment]
It was created with https://github.com/ScottKwang/CodeWithFriends-Spring2020/commit/586bbcdd6bcbceefe46bbce68b026491e8a42901.

**Comment by ScottKwang** [comment]
My mistake I left the `projects/` directory empty and did not commit it. It should be there now.
